### ISSUE TITLE
Applovin support for rewarded ads

### ISSUE THREAD

**Issue by totebo** [gideros/giderosplugins#5]
An addition to the Ads Interface for Applovin to support rewarded ads.

iOS implementation:
https://www.applovin.com/integration#iosRewardedVids

Android implementation:
https://www.applovin.com/integration#androidRewardedVids

Forum: http://giderosmobile.com/forum/discussion/5773/applovin-rewarded-videos#Item_13

**Comment by ar2rsawseen** [comment]
Added

**Comment by totebo** [comment]
Fantastic! Will check tomorrow.
