### ISSUE TITLE
Applovin AD_DISMISSED not firing

### ISSUE THREAD

**Issue by totebo** [gideros/giderosplugins#6]
The AD_DISMISSED event is not firing for Applovin in Ads Interface.

Forum: http://giderosmobile.com/forum/discussion/5385/applovin-ad_dismissed-not-fired-on-ios#Item_17

**Comment by ar2rsawseen** [comment]
Fixed ;)

**Comment by totebo** [comment]
Awesome! Will test tomorrow.
